#!/usr/bin/python3

import socket
import sys
import os
path = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + '/'
sys.path.append(path)
import config

params = sys.argv[1:]
if len(params) > 0:
    if params[0] == '{':
        params = params[0]
    else:
        params = ' '.join(params)
else:
    print('You must specify action from list: ' + ', '.join(config.actions))
    sys.exit(1)

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    sock.connect((config.server['address'], config.server['port']))
    sock.sendall(bytes(params, 'utf-8'))

    response = ''
    while True:
        data = sock.recv(1024)
        if not data:
            break
        else:
            response += str(data, 'utf-8')
    print(response)

except Exception as e:
    print(e)

finally:
    sock.close()
