#!/usr/bin/python3

import sys
import os
import random

path = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + '/'
sys.path.append(path)
import logging
import config
from actions.scan import Scan

# Scan users
users = os.listdir(config.path['home'])
random.shuffle(users)
for user in users:
    if os.path.isdir(config.path['home'] + user):
        Scan(user, {}).shell()
        response = Scan(user, {'command': 'aibolit', 'report': 1}).process()
        logging.info('Found: {1}'.format(user, response['data']['info']['infected']))
