#!/usr/bin/python3

import os
import sys
import urllib.request
import urllib.error
path = os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + '/'
sys.path.append(path)
import config
import utils

# Remove old user backups
utils.run(
    'find {0} -maxdepth 1 -name "*.zip" -mmin +{1} '.format(
        config.path['user']['backups'],
        str(config.watchdog['keep_backups'])
    ) + '-exec rm {} \;'
)

# Remove old files from Sprut.io downloads
utils.run('find /opt/sprutio/downloads/* -maxdepth 0 -mmin +1440 -exec rm -rf {} \;')

# Check sites availability
host = config.server['domain']
url = 'http://' + host + '/check'
try:
    response = urllib.request.urlopen(url, timeout=config.watchdog['timeout'])
    data = response.read().decode("utf-8")
    if data != 'All OK':
        utils.restart_services(host, data)
except urllib.request.HTTPError as e:
    if e.code != 404:
        utils.restart_services(host, str(e))
